insert into actors (id, name, birth_date, nationality) values (1, 'Conni Delaney', '2022-10-11', 'Afghanistan');
insert into actors (id, name, birth_date, nationality) values (2, 'Wat Dando', '2022-10-11', 'Argentina');
insert into actors (id, name, birth_date, nationality) values (3, 'Antonietta Rosellini', '2022-12-31', 'China');
insert into actors (id, name, birth_date, nationality) values (4, 'Dal Snawden', '2022-12-06', 'Philippines');
insert into actors (id, name, birth_date, nationality) values (5, 'Samara Farren', '2022-07-18', 'Ukraine');
insert into actors (id, name, birth_date, nationality) values (6, 'Barney Griswood', '2022-08-02', 'Russia');
insert into actors (id, name, birth_date, nationality) values (7, 'Sutherlan Denmead', '2022-05-28', 'Poland');
insert into actors (id, name, birth_date, nationality) values (8, 'Gisele Gavini', '2022-11-28', 'Thailand');
insert into actors (id, name, birth_date, nationality) values (9, 'Johannah Harland', '2023-04-22', 'Iraq');
insert into actors (id, name, birth_date, nationality) values (10, 'Quent Noden', '2022-11-28', 'Belarus');
insert into actors (id, name, birth_date, nationality) values (11, 'Ariella Normand', '2022-08-20', 'Sweden');
insert into actors (id, name, birth_date, nationality) values (12, 'Emilia Kertess', '2022-09-27', 'Japan');
insert into actors (id, name, birth_date, nationality) values (13, 'Trey De Domenico', '2023-04-16', 'Poland');
insert into actors (id, name, birth_date, nationality) values (14, 'Steven Waymont', '2022-12-21', 'Nigeria');
insert into actors (id, name, birth_date, nationality) values (15, 'Shaughn McBeth', '2022-11-02', 'United States');
insert into actors (id, name, birth_date, nationality) values (16, 'Sisile Wadforth', '2022-05-13', 'Poland');
insert into actors (id, name, birth_date, nationality) values (17, 'Kordula Proswell', '2022-06-11', 'Morocco');
insert into actors (id, name, birth_date, nationality) values (18, 'Chancey Gainsborough', '2022-09-02', 'Greece');
insert into actors (id, name, birth_date, nationality) values (19, 'Bambie Balderson', '2022-12-02', 'Indonesia');
insert into actors (id, name, birth_date, nationality) values (20, 'Charin Brownsell', '2022-08-28', 'China');
insert into actors (id, name, birth_date, nationality) values (21, 'Dyane Thornborrow', '2023-03-30', 'Sweden');
insert into actors (id, name, birth_date, nationality) values (22, 'Ainslee Pilsbury', '2023-01-12', 'Indonesia');
insert into actors (id, name, birth_date, nationality) values (23, 'Jacquenette Orriss', '2023-02-16', 'Vietnam');
insert into actors (id, name, birth_date, nationality) values (24, 'Wendie Rainton', '2022-08-17', 'Macedonia');
insert into actors (id, name, birth_date, nationality) values (25, 'Guthrey Farreil', '2022-11-23', 'Russia');
insert into actors (id, name, birth_date, nationality) values (26, 'Mady Karmel', '2023-03-08', 'Japan');
insert into actors (id, name, birth_date, nationality) values (27, 'Leonelle Marmion', '2022-11-08', 'China');
insert into actors (id, name, birth_date, nationality) values (28, 'Marve Barnsdall', '2022-05-11', 'Pakistan');
insert into actors (id, name, birth_date, nationality) values (29, 'Wenonah Sawbridge', '2022-05-28', 'Mexico');
insert into actors (id, name, birth_date, nationality) values (30, 'Vick Cozby', '2022-07-25', 'France');
insert into actors (id, name, birth_date, nationality) values (31, 'Donnell Treen', '2022-09-28', 'Niger');
insert into actors (id, name, birth_date, nationality) values (32, 'Blake Mettrick', '2022-09-06', 'China');
insert into actors (id, name, birth_date, nationality) values (33, 'Dorie Spiring', '2022-06-19', 'Indonesia');
insert into actors (id, name, birth_date, nationality) values (34, 'Wandie Farnan', '2022-07-31', 'China');
insert into actors (id, name, birth_date, nationality) values (35, 'Lianna Ormiston', '2022-10-21', 'Germany');
insert into actors (id, name, birth_date, nationality) values (36, 'Garreth Villar', '2022-10-06', 'Poland');
insert into actors (id, name, birth_date, nationality) values (37, 'Dionis Chesser', '2022-05-21', 'Indonesia');
insert into actors (id, name, birth_date, nationality) values (38, 'Elihu Shottin', '2022-05-03', 'Malaysia');
insert into actors (id, name, birth_date, nationality) values (39, 'Edyth Flintoff', '2022-11-04', 'North Korea');
insert into actors (id, name, birth_date, nationality) values (40, 'Donnie Tumayan', '2022-06-11', 'Portugal');
insert into actors (id, name, birth_date, nationality) values (41, 'Tully Hurich', '2022-08-20', 'Thailand');
insert into actors (id, name, birth_date, nationality) values (42, 'Anneliese Foukx', '2022-11-27', 'Russia');
insert into actors (id, name, birth_date, nationality) values (43, 'Erinna Vasilischev', '2022-07-01', 'Dominican Republic');
insert into actors (id, name, birth_date, nationality) values (44, 'Gerhardt Readwing', '2022-09-27', 'Zambia');
insert into actors (id, name, birth_date, nationality) values (45, 'Connie Coda', '2022-07-01', 'Morocco');
insert into actors (id, name, birth_date, nationality) values (46, 'Lena Poynzer', '2022-08-10', 'Russia');
insert into actors (id, name, birth_date, nationality) values (47, 'Danella Morphew', '2022-09-25', 'Jamaica');
insert into actors (id, name, birth_date, nationality) values (48, 'Rozamond Rivers', '2022-10-22', 'Japan');
insert into actors (id, name, birth_date, nationality) values (49, 'Cassey Smaile', '2023-04-18', 'Russia');
insert into actors (id, name, birth_date, nationality) values (50, 'Ruben Nornasell', '2022-05-03', 'Russia');
insert into actors (id, name, birth_date, nationality) values (51, 'Pyotr Seamons', '2022-05-29', 'Indonesia');
insert into actors (id, name, birth_date, nationality) values (52, 'Samantha Giraudo', '2022-10-28', 'Russia');
insert into actors (id, name, birth_date, nationality) values (53, 'Shana Tower', '2023-04-07', 'Spain');
insert into actors (id, name, birth_date, nationality) values (54, 'Sydney Duligal', '2023-03-23', 'China');
insert into actors (id, name, birth_date, nationality) values (55, 'Berta Stoven', '2023-04-04', 'Ukraine');
insert into actors (id, name, birth_date, nationality) values (56, 'Nilson Connold', '2022-06-13', 'Honduras');
insert into actors (id, name, birth_date, nationality) values (57, 'Findley Rollason', '2022-08-11', 'Poland');
insert into actors (id, name, birth_date, nationality) values (58, 'Corliss Wolstenholme', '2023-01-10', 'China');
insert into actors (id, name, birth_date, nationality) values (59, 'Kerianne Lorens', '2022-11-16', 'Indonesia');
insert into actors (id, name, birth_date, nationality) values (60, 'Flossy Gasnell', '2022-09-09', 'Czech Republic');
insert into actors (id, name, birth_date, nationality) values (61, 'Billy Chittock', '2022-06-24', 'Ukraine');
insert into actors (id, name, birth_date, nationality) values (62, 'Bryn Brumbie', '2022-10-13', 'Costa Rica');
insert into actors (id, name, birth_date, nationality) values (63, 'Rupert Peele', '2022-06-04', 'Poland');
insert into actors (id, name, birth_date, nationality) values (64, 'Ellery Titheridge', '2022-10-13', 'China');
insert into actors (id, name, birth_date, nationality) values (65, 'Charlotte Szapiro', '2022-08-05', 'Brazil');
insert into actors (id, name, birth_date, nationality) values (66, 'Yoshi Izod', '2022-10-03', 'China');
insert into actors (id, name, birth_date, nationality) values (67, 'Ardenia Penhalurick', '2022-07-18', 'Indonesia');
insert into actors (id, name, birth_date, nationality) values (68, 'Leyla Squier', '2023-03-24', 'Haiti');
insert into actors (id, name, birth_date, nationality) values (69, 'Christy Dorling', '2022-09-06', 'Thailand');
insert into actors (id, name, birth_date, nationality) values (70, 'Kingsley Belhome', '2022-11-30', 'Madagascar');
insert into actors (id, name, birth_date, nationality) values (71, 'Rosene Counter', '2023-02-28', 'El Salvador');
insert into actors (id, name, birth_date, nationality) values (72, 'Honey Lampbrecht', '2022-11-22', 'China');
insert into actors (id, name, birth_date, nationality) values (73, 'Rowe Leyborne', '2023-02-04', 'Czech Republic');
insert into actors (id, name, birth_date, nationality) values (74, 'Hershel Kisbey', '2022-07-11', 'Russia');
insert into actors (id, name, birth_date, nationality) values (75, 'Hope Cavan', '2023-02-07', 'Indonesia');
insert into actors (id, name, birth_date, nationality) values (76, 'Hannie Heindrich', '2023-02-08', 'Indonesia');
insert into actors (id, name, birth_date, nationality) values (77, 'Shelton Kilkenny', '2022-12-03', 'Montenegro');
insert into actors (id, name, birth_date, nationality) values (78, 'Cori Sketch', '2022-05-09', 'Norway');
insert into actors (id, name, birth_date, nationality) values (79, 'Mae Oag', '2023-03-23', 'Malaysia');
insert into actors (id, name, birth_date, nationality) values (80, 'Sabrina Watkinson', '2023-02-12', 'China');
insert into actors (id, name, birth_date, nationality) values (81, 'Carie Huggard', '2023-04-19', 'Sweden');
insert into actors (id, name, birth_date, nationality) values (82, 'Noelle Wardingley', '2022-06-09', 'Ukraine');
insert into actors (id, name, birth_date, nationality) values (83, 'Bram Ethridge', '2022-11-13', 'Portugal');
insert into actors (id, name, birth_date, nationality) values (84, 'Jecho Synan', '2022-06-27', 'Albania');
insert into actors (id, name, birth_date, nationality) values (85, 'Maritsa Challen', '2022-06-15', 'Sweden');
insert into actors (id, name, birth_date, nationality) values (86, 'Tann West-Frimley', '2022-09-08', 'Belgium');
insert into actors (id, name, birth_date, nationality) values (87, 'Edee Pesek', '2022-08-27', 'Russia');
insert into actors (id, name, birth_date, nationality) values (88, 'Ardeen Blackster', '2022-06-10', 'Indonesia');
insert into actors (id, name, birth_date, nationality) values (89, 'Edy Rhoddie', '2022-05-14', 'Colombia');
insert into actors (id, name, birth_date, nationality) values (90, 'Isaiah Boig', '2022-12-23', 'Pakistan');
insert into actors (id, name, birth_date, nationality) values (91, 'Letta Parratt', '2022-06-05', 'Poland');
insert into actors (id, name, birth_date, nationality) values (92, 'Ethelin Czajka', '2022-10-15', 'China');
insert into actors (id, name, birth_date, nationality) values (93, 'Cherin Marfell', '2023-01-13', 'Philippines');
insert into actors (id, name, birth_date, nationality) values (94, 'Natalya de Clerk', '2022-07-18', 'Finland');
insert into actors (id, name, birth_date, nationality) values (95, 'Ansell Talloe', '2022-07-06', 'Peru');
insert into actors (id, name, birth_date, nationality) values (96, 'Irvin Kendred', '2022-12-27', 'Netherlands');
insert into actors (id, name, birth_date, nationality) values (97, 'Willie Roskams', '2022-07-30', 'Laos');
insert into actors (id, name, birth_date, nationality) values (98, 'Daisi Mitrikhin', '2022-04-25', 'Russia');
insert into actors (id, name, birth_date, nationality) values (99, 'Kellina Izen', '2022-11-03', 'Burkina Faso');
insert into actors (id, name, birth_date, nationality) values (100, 'Bel Orys', '2022-07-19', 'United States');
